In [18]:
from variant_funcs import met_variant

In [8]:
import Bio
import polars as pl

In [19]:

df = met_variant(
    bam_path="/Users/michaeltisza/mike_tisza/sandbox/variant_stuff/h1n1/S9FPA8.p1700.sort.bam",
    fasta_path="/Users/michaeltisza/mike_tisza/sandbox/variant_stuff/h1n1/reference/H1N1_reference.fasta",
    gff_path="/Users/michaeltisza/mike_tisza/sandbox/variant_stuff/h1n1/reference/gff/GCA_039113225.1_ASM3911322v1_genomic.gff",
    min_base_qual=20,
    min_depth=10,
)
print(df.head())

shape: (5, 23)
┌────────────┬──────┬─────┬─────┬───┬────────┬─────────────┬───────────┬────────────┐
│ contig     ┆ pos  ┆ ref ┆ alt ┆ … ┆ aa_alt ┆ codon_index ┆ codon_pos ┆ effect     │
│ ---        ┆ ---  ┆ --- ┆ --- ┆   ┆ ---    ┆ ---         ┆ ---       ┆ ---        │
│ str        ┆ i64  ┆ str ┆ str ┆   ┆ str    ┆ i64         ┆ i64       ┆ str        │
╞════════════╪══════╪═════╪═════╪═══╪════════╪═════════════╪═══════════╪════════════╡
│ LC778481.1 ┆ 1758 ┆ G   ┆ A   ┆ … ┆ K      ┆ 586         ┆ 3         ┆ synonymous │
│ LC778481.1 ┆ 1800 ┆ T   ┆ C   ┆ … ┆ N      ┆ 600         ┆ 3         ┆ synonymous │
│ LC778481.1 ┆ 1806 ┆ A   ┆ G   ┆ … ┆ R      ┆ 602         ┆ 3         ┆ synonymous │
│ LC778481.1 ┆ 1822 ┆ G   ┆ C   ┆ … ┆ Q      ┆ 608         ┆ 1         ┆ missense   │
│ LC778481.1 ┆ 1827 ┆ C   ┆ G   ┆ … ┆ V      ┆ 609         ┆ 3         ┆ synonymous │
└────────────┴──────┴─────┴─────┴───┴────────┴─────────────┴───────────┴────────────┘

In [20]:
df

shape: (6, 23)
┌────────────┬──────┬─────┬─────┬───┬────────┬─────────────┬───────────┬────────────┐
│ contig     ┆ pos  ┆ ref ┆ alt ┆ … ┆ aa_alt ┆ codon_index ┆ codon_pos ┆ effect     │
│ ---        ┆ ---  ┆ --- ┆ --- ┆   ┆ ---    ┆ ---         ┆ ---       ┆ ---        │
│ str        ┆ i64  ┆ str ┆ str ┆   ┆ str    ┆ i64         ┆ i64       ┆ str        │
╞════════════╪══════╪═════╪═════╪═══╪════════╪═════════════╪═══════════╪════════════╡
│ LC778481.1 ┆ 1758 ┆ G   ┆ A   ┆ … ┆ K      ┆ 586         ┆ 3         ┆ synonymous │
│ LC778481.1 ┆ 1800 ┆ T   ┆ C   ┆ … ┆ N      ┆ 600         ┆ 3         ┆ synonymous │
│ LC778481.1 ┆ 1806 ┆ A   ┆ G   ┆ … ┆ R      ┆ 602         ┆ 3         ┆ synonymous │
│ LC778481.1 ┆ 1822 ┆ G   ┆ C   ┆ … ┆ Q      ┆ 608         ┆ 1         ┆ missense   │
│ LC778481.1 ┆ 1827 ┆ C   ┆ G   ┆ … ┆ V      ┆ 609         ┆ 3         ┆ synonymous │
│ LC778481.1 ┆ 1875 ┆ T   ┆ C   ┆ … ┆ C      ┆ 625         ┆ 3         ┆ synonymous │
└────────────┴──────┴─────┴─────┴───┴────────┴─────────────┴───────────┴────────────┘

In [21]:
h3n2_df = met_variant(
    bam_path = "/Users/michaeltisza/mike_tisza/sandbox/variant_stuff/h3n2/fall_2024_winter_2025_TEPHI_pools.H3N2.sort.bam",
    fasta_path = "/Users/michaeltisza/mike_tisza/sandbox/variant_stuff/h3n2/reference/LACPHL-INF00603.fasta",
    gff_path = "/Users/michaeltisza/mike_tisza/sandbox/variant_stuff/h3n2/reference/GCA_046438425.1_ASM4643842v1_genomic.gff"
)

In [22]:
h3n2_df.filter(pl.col("af") > 0.1)

shape: (118, 23)
┌────────────┬──────┬─────┬─────┬───┬────────┬─────────────┬───────────┬────────────┐
│ contig     ┆ pos  ┆ ref ┆ alt ┆ … ┆ aa_alt ┆ codon_index ┆ codon_pos ┆ effect     │
│ ---        ┆ ---  ┆ --- ┆ --- ┆   ┆ ---    ┆ ---         ┆ ---       ┆ ---        │
│ str        ┆ i64  ┆ str ┆ str ┆   ┆ str    ┆ i64         ┆ i64       ┆ str        │
╞════════════╪══════╪═════╪═════╪═══╪════════╪═════════════╪═══════════╪════════════╡
│ PQ595686.1 ┆ 193  ┆ G   ┆ A   ┆ … ┆ S      ┆ 65          ┆ 1         ┆ missense   │
│ PQ595686.1 ┆ 242  ┆ C   ┆ A   ┆ … ┆ K      ┆ 81          ┆ 2         ┆ missense   │
│ PQ595686.1 ┆ 261  ┆ A   ┆ G   ┆ … ┆ L      ┆ 87          ┆ 3         ┆ synonymous │
│ PQ595686.1 ┆ 303  ┆ C   ┆ T   ┆ … ┆ D      ┆ 101         ┆ 3         ┆ synonymous │
│ PQ595686.1 ┆ 387  ┆ T   ┆ C   ┆ … ┆ A      ┆ 129         ┆ 3         ┆ synonymous │
│ …          ┆ …    ┆ …   ┆ …   ┆ … ┆ …      ┆ …           ┆ …         ┆ …          │
│ PQ595693.1 ┆ 822  ┆ G   ┆ A   ┆ … ┆ A      ┆ 274         ┆ 3         ┆ synonymous │
│ PQ595693.1 ┆ 1098 ┆ G   ┆ A   ┆ … ┆ V      ┆ 366         ┆ 3         ┆ synonymous │
│ PQ595693.1 ┆ 1215 ┆ T   ┆ C   ┆ … ┆ S      ┆ 405         ┆ 3         ┆ synonymous │
│ PQ595693.1 ┆ 1400 ┆ C   ┆ T   ┆ … ┆ M      ┆ 467         ┆ 2         ┆ missense   │
│ PQ595693.1 ┆ 1701 ┆ C   ┆ T   ┆ … ┆ N      ┆ 567         ┆ 3         ┆ synonymous │
└────────────┴──────┴─────┴─────┴───┴────────┴─────────────┴───────────┴────────────┘